### ISSUE TITLE
生成个人数据出错

### ISSUE THREAD

**Issue by wukoufan** [foodgame/foodgame.github.io#10]
L大佬好，在更新了“虎虎迎春池”的资料之后，导出个人数据时会出现个别厨师对应错误的问题。目前发现“1182号唐伏鹿”与“1173号裘小白”的“已修、已有、厨具”数据出错，即这两位厨师的数据在导出时是互换的。
![image](https://user-images.githubusercontent.com/65391054/151073737-8233c169-b5d4-4f6d-884c-c3ab484ad4ce.png)
![image](https://user-images.githubusercontent.com/65391054/151073778-c7e73ff2-5f88-4045-b6ff-9287f735bd10.png)
应该是由foodgame.github.io/data/data.min.json中数据错误导致的。期盼修改！

**Comment by foodgame** [comment]
Hi, 不用在意导出数据里的编号, 你用导出的数据再导入并不会出现互换的情况. 其实那个编号才是真正不变的编号, 比如一些后厨菜在游戏中的图鉴编号每次出新池都会变动, 所以导出数据里用的编号是真正的编号, 而不是游戏中的图鉴编号.

**Comment by wukoufan** [comment]
感谢回复！我在Google Spreadsheet做了一个自用表格，数据是导入您这里的json文件，之前注意到了后厨菜的问题做过自动的动态调整，而这次虎虎池的厨师id的情况是第一次出现，最后是手动进行了调整。
