### ISSUE TITLE
提一个建议，能否添加缓存已有收集的功能

### ISSUE THREAD

**Issue by RyinSummers** [foodgame/foodgame.github.io#4]
首先向开发图鉴的大佬递茶！
举一个例子，比如想查找某厨师做哪道菜效率最高，很多时候排在前面的菜谱都是我没有的。能否对每个用户出一个功能，在本地存储一下他已经拥有的菜谱/厨师/等等，这样便于筛选。（灵感来源是http://seal100x.github.io/nikkiup2u3 奇迹暖暖的图鉴，有备份游戏收集度的功能）

**Comment by foodgame** [comment]
没有玩过奇迹暖暖, 打开图签看的我好晕... 不过应该知道你想要什么了, 等抽空我做一下.

**Comment by foodgame** [comment]
感谢提的建议, 功能已加上.╰(●’◡’●)╯
