### ISSUE TITLE
同时支持多个查找条件

### ISSUE THREAD

**Issue by swgr424** [foodgame/foodgame.github.io#5]
大佬好~

我个人用图鉴的时候会有一类特殊的需求，比如某些主线需要查找『有咖喱**或**笋』的菜，或者比如厨神大赛时『从计算器中框选出一个菜名清单，然后快速搜出其中哪些菜是我已有的』这样的功能。简单来说，就是在匹配时输入"a,b"或者"a b"，然后筛选出所有包含"a"**或**"b"的条目。

我自己实现了一下这个功能，目前支持了各种.search-box（比如厨师页面查找厨师）和使用bootstrap-select里data-live-search的下拉菜单（比如厨师页面选择菜谱）。commit在[这里](https://github.com/swgr424/foodgame.github.io/commit/59865ea0442c2ffac6c8fda055f2736ba24ea81c)。
大佬要是觉得有意义我就去发pull request。不过在下拉菜单里实现这个功能涉及到了对bootstrap-select的魔改（我本职不是前端所以不知道有没有更好的办法），不知道适不适合合并进来~

**Comment by foodgame** [comment]
Sorry, 很久没有登陆github，没看到issue。你提的这2个需求现在的图鉴差不多已经有了。

关于多个食材搜索，原先做了个可用搜索框来查找多个食材的功能，但做好后又觉得很少会有人看说明页，也就不知道怎么同时查找多个， 所以改为了现在的列表选择食材并过滤。

计算器有一个“已有”按钮，用来只显示自己有的厨师/菜谱。

Github很少登陆，如果有什么问题可以群里找我
